# permissions for end users to edit controlplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlplane-editor-role
rules:
- apiGroups:
  - controlplane.openstack.org
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.openstack.org
  resources:
  - controlplanes/status
  verbs:
  - get
