apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openstackclusters.openstackcluster.openstack.org
spec:
  group: openstackcluster.openstack.org
  names:
    kind: OpenStackCluster
    listKind: OpenStackClusterList
    plural: openstackclusters
    singular: openstackcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OpenStackCluster is the Schema for the openstackclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OpenStackClusterSpec defines the desired state of OpenStackCluster
          type: object
        status:
          description: OpenStackClusterStatus defines the observed state of OpenStackCluster
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
