apiVersion: v1
kind: Secret
metadata:
  name: glance-secret
  namespace: {{ .Namespace }}
stringData:
  TransportUrl: rabbit://osp:passw0rd@rabbit.openstack.svc:5672/?ssl=0
  DatabasePassword: openstack
  GlanceKeystoneAuthPassword: openstack
